### ISSUE TITLE
Application attachBaseContext崩溃

### ISSUE THREAD

**Issue by pumatus** [MichaelJokAr/MultiLanguages#1]
@Override
	protected void attachBaseContext(Context base) {
		MultiDex.install(this);
//		 保存系统选择语言
		LocalManagerUtil.INSTANCE.saveSystemCurrentLanguage();
		super.attachBaseContext(LocalManageUtils.setLocal(base));
	}

**Comment by MichaelJokAr** [comment]
有log吗？谢谢

**Comment by pumatus** [comment]
解决了，是我这边判断那个TAG_LANGUAGE值是空的，原因是之前自己写的sp没有实例化！
