### ISSUE TITLE
文档写的不太清楚

### ISSUE THREAD

**Issue by mr-shitou** [MichaelJokAr/MultiLanguages#11]
你好，我在项目中使用了这个开源库
但是，有个问题想问一下
plugin的作用是什么，第三方库语言变换么
我之前在使用的过程中就出现集成第三方SDK导致Service创建失败，找了好久才发现是插件的原因，看到#7  升级了插件才解决了问题
所以，希望可以将文档写的更详细些，把改变应用内语言和第三方库分离开，毕竟有些第三方库并不能了解的很清楚，提个小建议
非常感谢开源这个库，这个库是目前来说，比较新并且star也算比较高的，希望能维护的越来越好
如果需要帮助一起维护这个库的话，我也希望可以尽自己的一份力
加油⛽️

**Comment by MichaelJokAr** [comment]
非常抱歉之前的Service 问题，plugin的作用是在activity、service、intentService里自动生成
```
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(MultiLanguage.setLocal(newBase));
    }
```
这个方法
