### ISSUE TITLE
 FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:transformClassesWithMultiLanguagesForDebug'. > This feature requires ASM6

### ISSUE THREAD

**Issue by ouwp** [MichaelJokAr/MultiLanguages#12]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultiLanguagesForDebug'.
> This feature requires ASM6

**Comment by ouwp** [comment]
v0.0.7

**Comment by MichaelJokAr** [comment]
what's your gradle version?

**Comment by ouwp** [comment]
com.android.tools.build:gradle:3.5.2
https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by MichaelJokAr** [comment]
暂时没遇到你这种情况，要不你别引用```plugin```插件了。在需要的activity、service 里重写```attachBaseContext```方法，如下
```
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(MultiLanguage.setLocal(newBase))
    }
```

**Comment by ouwp** [comment]
好的，非常感谢

> 暂时没遇到你这种情况，要不你别引用`plugin`插件了。在需要的activity、service 里重写`attachBaseContext`方法，如下
> 
> ```
>     override fun attachBaseContext(newBase: Context?) {
>         super.attachBaseContext(MultiLanguage.setLocal(newBase))
>     }
> ```
