### ISSUE TITLE
接入项目之后 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithInstantRunForDebug'

### ISSUE THREAD

**Issue by HandSomeMaster** [MichaelJokAr/MultiLanguages#13]
如题 接入依赖以后 我运行项目就会报错
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithInstantRunForDebug'
 java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.IllegalStateException: java.lang.IllegalStateException
不知道有没有人遇到 我不知道怎么解决

**Comment by MichaelJokAr** [comment]
关闭InstantRun试试
