### ISSUE TITLE
无法编译 Cause: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by 704480904** [MichaelJokAr/MultiLanguages#15]
![image](https://user-images.githubusercontent.com/6984303/69771752-dac9a180-11c8-11ea-8167-163d59018891.png)

**Comment by MichaelJokAr** [comment]
麻烦贴出具体信息，谢谢

**Comment by 704480904** [comment]
应该是Instance Run 导致的问题，我升级了Android studio 版本到3.5.2 就可以了，3.5.2 默认好像没有instace run

**Comment by MichaelJokAr** [comment]
是的，暂时不支持Instance Run
