### ISSUE TITLE
kotlin 语言编译不成功

### ISSUE THREAD

**Issue by lixiaohui1090** [MichaelJokAr/MultiLanguages#16]
父类activity 使用kotlin 编写 无法进行编译  将会  skip BaseActivity

**Comment by MichaelJokAr** [comment]
是的，暂时还不支持kotlin 自动重写```attachBaseContext```方法，可以先手动重写
```super.attachBaseContext(MultiLanguage.setLocal(newBase))```

**Comment by MichaelJokAr** [comment]
试了下可以编译成功呀。请问build窗口里有输出类似日志么
![image](https://user-images.githubusercontent.com/8246218/69898709-d1dafa80-1397-11ea-8a1c-74542ff7c65e.png)
