### ISSUE TITLE
向大佬们求解了，在读取assets中.json文件时失效

### ISSUE THREAD

**Issue by ErenSnow** [MichaelJokAr/MultiLanguages#17]
![image](https://user-images.githubusercontent.com/30656290/74123279-3c66ad00-4c09-11ea-94fb-b6a8b03ee453.png)
在切换语言时，.json文件切换失效，只有完全杀死后台才能有效，向大佬们求解了！！！

**Comment by MichaelJokAr** [comment]
怎么解决的？
