### ISSUE TITLE
第三方的SDK和控件没有更改

### ISSUE THREAD

**Issue by wanghan5950** [MichaelJokAr/MultiLanguages#2]
App的语言是更改成功了，但是第三方的SDK和控件的语言依然和系统一致，这是什么原因？按理说在Application的attachBaseContext(Context base)方法中设置的应该可以更改第三方的啊？

**Comment by kinpowoo** [comment]
作者说只有实现了 BaseActivity的类语言才会更改，第三方控件肯定是没有继承你自己这个BaseActivity的

**Comment by luomaa** [comment]
解决了 其中有个类没有继承base导致

**Comment by MichaelJokAr** [comment]
@wanghan5950 2.0版本现已支持第三方sdk多语言切换（前提是本地有对应的语言资源文件）
