### ISSUE TITLE
混淆出错

### ISSUE THREAD

**Issue by imyyq-star** [MichaelJokAr/MultiLanguages#6]
AGPBI: {"kind":"error","text":"Illegal invoke-super to void android.app.IntentService.attachBaseContext(android.content.Context) from class com.google.firebase.components.ComponentDiscoveryService","sources":[{"file":"F:\\**\\**\\app\\build\\intermediates\\transforms\\MultiLanguages\\release\\42.jar"}],"tool":"D8"}

> Task :app:transformClassesAndResourcesWithR8ForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

请问这种是什么情况？？？

Android Studio 3.5
Gradle 3.4.2

**Comment by MichaelJokAr** [comment]
@imyyq-star 麻烦把混淆文件发下，谢谢

**Comment by MichaelJokAr** [comment]
我自己试了下混淆是没问题的，你混淆代码里有keep service么？
