### ISSUE TITLE
升级androidx的v7包到1.1.0 会出现国际化错乱

### ISSUE THREAD

**Issue by xiaozhuge007** [MichaelJokAr/MultiLanguages#9]
androidx.appcompat:appcompat:1.1.0
设置下边夜间模式AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES); 
 这个包 1.0.2 没问题 1.1.0会错乱，情况就是代码设置的可以，xml里直接设置的无效

AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES); 白天模式下就是正常的

**Comment by MichaelJokAr** [comment]
已修复，请更新到v0.0.6版本
